// Package shape contains generators for synthetic geometries useful for
// benchmarks, fuzz seeds, and visual tests. It is a Go port of the JTS
// org.locationtech.jts.shape.* family of builders.
package shape

import (
	"math/rand/v2"

	"github.com/exergy-dev/go-topology-suite/geom"
)

// Option configures a generator. Options are accepted as variadic
// arguments by every public function in this package.
type Option func(*config)

type config struct {
	rng *rand.Rand
}

// WithSeed makes the generator deterministic. Without it, generators use
// the global math/rand/v2 source.
//
// JTS RandomPointsBuilder uses Math.random() and is not seedable; this
// option is a Go-friendly addition.
func WithSeed(seed uint64) Option {
	return func(c *config) {
		// rand.New requires a Source; PCG is the default v2 source.
		c.rng = rand.New(rand.NewPCG(seed, seed^0x9E3779B97F4A7C15))
	}
}

func newConfig(opts []Option) *config {
	c := &config{}
	for _, opt := range opts {
		opt(c)
	}
	return c
}

// random64 returns the next float in [0,1). Falls back to the global
// math/rand/v2 source when the caller did not pass WithSeed.
func (c *config) random64() float64 {
	if c.rng != nil {
		return c.rng.Float64()
	}
	return rand.Float64()
}

// RandomPoints returns n points distributed uniformly in env.
//
// JTS: org.locationtech.jts.shape.random.RandomPointsBuilder (rectangular
// extent path).
func RandomPoints(n int, env geom.Envelope, opts ...Option) []geom.XY {
	if n <= 0 || env.IsEmpty() {
		return nil
	}
	cfg := newConfig(opts)
	pts := make([]geom.XY, n)
	w := env.Width()
	h := env.Height()
	for i := 0; i < n; i++ {
		pts[i] = geom.XY{
			X: env.MinX + w*cfg.random64(),
			Y: env.MinY + h*cfg.random64(),
		}
	}
	return pts
}

// RandomPointsInPolygon returns n points uniformly distributed inside p.
// Points are generated by rejection sampling against the polygon's
// bounding envelope; degenerate (zero-area) polygons return nil to avoid
// an infinite loop.
//
// JTS: org.locationtech.jts.shape.random.RandomPointsBuilder (polygonal
// mask path).
func RandomPointsInPolygon(n int, p *geom.Polygon, opts ...Option) []geom.XY {
	if n <= 0 || p == nil || p.IsEmpty() {
		return nil
	}
	env := p.Envelope()
	if env.IsEmpty() || env.Width() == 0 || env.Height() == 0 {
		return nil
	}
	cfg := newConfig(opts)
	w := env.Width()
	h := env.Height()
	shell := p.ExteriorRing()
	holes := p.InteriorRings()

	pts := make([]geom.XY, 0, n)
	for len(pts) < n {
		c := geom.XY{
			X: env.MinX + w*cfg.random64(),
			Y: env.MinY + h*cfg.random64(),
		}
		if !pointInRing(c, shell) {
			continue
		}
		inHole := false
		for _, h := range holes {
			if pointInRing(c, h) {
				inHole = true
				break
			}
		}
		if inHole {
			continue
		}
		pts = append(pts, c)
	}
	return pts
}

// pointInRing performs a ray-cast point-in-ring test. ring is expected to
// be closed (first == last). Boundary points are counted as inside.
func pointInRing(p geom.XY, ring []geom.XY) bool {
	if len(ring) < 4 {
		return false
	}
	inside := false
	n := len(ring) - 1
	for i := 0; i < n; i++ {
		a := ring[i]
		b := ring[i+1]
		if (a.Y > p.Y) != (b.Y > p.Y) {
			xint := a.X + (p.Y-a.Y)*(b.X-a.X)/(b.Y-a.Y)
			if p.X < xint {
				inside = !inside
			}
		}
	}
	return inside
}
